import type { Metadata } from "next";
import DashboardHeader from "../_components/dashboard-header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="px-8 py-6">
      <DashboardHeader />
      {children}
    </div>
  );
}
